### ISSUE TITLE
Process Map ends up backwards

### ISSUE THREAD

**Issue by bzeeeb** [gertjanssenswillen/processmapR#10]
Wanted to officially document what I saw here in case anyone else sees similar issue.  The minute I execute devtools::install_github("gertjanssenswillen/processmapr", dependencies=TRUE), I end up with the map essentially upside down (start is still on top and end on bottom).  Below was the code I attempted to execute:
```
data.map2 <- data %>%
  process_map(type_nodes = frequency(value = "absolute_case"), type_edges = performance(FUN = median, units = "mins"))
```
Along with the following error: 
Error in data.frame(id = 1:n, from = from, to = to, rel = rel, stringsAsFactors = FALSE) : arguments imply differing number of rows: 2, 0 In addition: Warning messages: 1: In bind_rows_(x, .id) : binding factor and character vector, coercing into character vector 2: In bind_rows_(x, .id) : binding character and factor vector, coercing into character vector 3: In min(x) : no non-missing arguments to min; returning Inf 4: In max(x) : no non-missing arguments to max; returning -Inf

**Comment by gertjanssenswillen** [comment]
Would it be possible to share (a snippet of) your data, or a something else that reproduces there issue? (Might also be done via mail if possible at all)

**Comment by bzeeeb** [comment]
Sent to your email a generic sample to test.
