### ISSUE TITLE
could not find function "set_global_graph_attrs"

### ISSUE THREAD

**Issue by Granini077** [gertjanssenswillen/processmapR#11]
Hey Guys,

after updating DiagrammeR to Version 1.0.0 I have a problem to create a process map with the processmapR package, wich is trying to use one of the contained functions:

>Log2 %>%
   process_map()
Error in set_global_graph_attrs(., attr = "rankdir", value = "LR", attr_type = "graph") : 
  could not find function "set_global_graph_attrs"

**Comment by gertjanssenswillen** [comment]
This problem should be solved when installing the latest version from github. There will be an updated version of processmapR on CRAN very soon.

**Comment by Granini077** [comment]
Wow that was quick :+1:  
I will switch to the version on github. 
Many greetings !
