### ISSUE TITLE
Please remove it from process_map

### ISSUE THREAD

**Issue by wfeijenOI** [gertjanssenswillen/processmapR#15]
There is a prompt when one asks for generation of a processmap with more than 750 traces. The problem is that this prompt stops knittr from doing its work. Please remove it from the function.

The next code creates the problem:

if(n_traces(eventlog) > 750) {
	message("You are about to draw a process map with a lot of traces.
			This might take a long time. Try to filter your event log. Are you sure you want to proceed?")
	answer <- readline("Y/N: ")

	if(answer != "Y")
		break()
}

**Comment by gertjanssenswillen** [comment]
In the github version (will be on cran this afternoon), there is a force argument to this function to override this precaution.

```
function (eventlog, type = frequency("absolute"), type_nodes = type, 
    type_edges = type, render = T, **force = F**) 
```
