### ISSUE TITLE
process_map output does not have nodes in rankdir order

### ISSUE THREAD

**Issue by felicitysplatt** [gertjanssenswillen/processmapR#27]
Process_map output doesn't appear to layout the graph correctly, e.g.

event_log %>%
  process_map(
    rankdir = "RL"
  )

produces a graph where the nodes seem to be randomly all over the place, and not in order from left-to-right for the most frequent path.

![processmapoutput](https://user-images.githubusercontent.com/12880192/45582366-cd8d0380-b8f1-11e8-98dc-8264f6dbe319.png)

Understand that this is probably caused by DiagrammeR, and maybe I could modify the DiagrammR Graph object myself to obtain a more intuitive rankdir. Have you seen this before?

**Comment by felicitysplatt** [comment]
I've been messing around in DiagrammeR to manually set the order - not fun, but appears to be the best solution (for now). Thank you for all your great work on processmapR :-)

**Comment by gertjanssenswillen** [comment]
Hi there. Indeed, processmapr itself does not have a large say at the layout of the maps. In case the behaviour is unstructured, the map tends to be unstructured too...

I'm happy you found a workaround using DiagrammeR. Could you maybe share it so that other users with similar issues can learn from it?

**Comment by felicitysplatt** [comment]
Didn't manage to go down the path of manually change the node positions in DiagrammeR this time, but may explore in the future. Thanks so much for your help and encouragement :-)

**Comment by gertjanssenswillen** [comment]
Its now possible to provide x-y coordinates for each activity. See #29 and description below. 

Added 'fixed_node_pos' option that can be used together with the neato layout engine. Nodes position is given in a second data frame as x, y coordinated and joined through the activity identifier.

Example usage:

library(eventdataR)
library(processmapR)

positions <- data.frame(act = c("Registration","Triage and Assessment","Blood test", "MRI SCAN", "X-Ray", "Discuss Results", "Check-out", "Start", "End"),
						x = c(2,4,6,7,6,9,11,0,14),
						y = c(0,0,-1,0,1,0,0,0,0),
						stringsAsFactors = F)

process_map(patients, fixed_node_pos = positions)
Useful for cases in which the position of nodes has semantics.

**Comment by felicitysplatt** [comment]
thank you @gertjanssenswillen !!!
