### ISSUE TITLE
add QUANTILE performance

### ISSUE THREAD

**Issue by AntonioSecchi** [gertjanssenswillen/processmapR#30]
Is it possible to integrate also the **QUANTILE** metric inside performance()?

As showed in the example below, I'm hoping to get from process_map or other graphs, the quantile performance evaluation. 
The classic **3rd**, **1st** qualtile for example, or better, the prefered quantile.
For example the number **0.32** for **32nd** occurrence.
Even better if avaiable for both, nodes and edges.

patients %>%
    process_map(performance(quantile, **0,32** , "days"))

Hope you the best
@gertjanssenswillen

**Comment by gertjanssenswillen** [comment]
Thank you for the suggestion. Added this just now for both nodes and edges, and can be used for all functions. 

Please note that you will have to specify the argumentname for arguments that are to be passed on the the aggregation function. They are captured by the ... argument added to performance.

For example:

```
patients %>%
    process_map(performance(quantile, probs = 0.32 , "days"))
```
You don't have to name the units argument for days, as this is the first specified argument (although it probably would be safer. All argument names that are not explicitly listed for the performance function will pass through to the aggregator (in this case quantile).

Also note that it will give a error if you try to provide more than 1 probabilty, as the process map currently only uses a single value. In future it will become possible to add secondary metrics, e.g. seeing both frequency and performance of activities (as in Disco).

Another example; function mean with trim argument.

```
patients %>%
     process_map(performance(mean, trim = 0.1))
```
