### ISSUE TITLE
precedence_matrix() types should be hyphen-separated

### ISSUE THREAD

**Issue by richierocks** [gertjanssenswillen/processmapR#36]
The `edeaR` resource metric levels are hyphen separated, for example `"resource-activity"`.

`precedence_matrix()` types are underscore separated, for example, `"relative_antecedent"`.

This should be made consistent.

**Comment by gertjanssenswillen** [comment]
Fixed. Underscore notation still accepted but throws a warning. 
Currently only this function by will be changed package-wide.
