### ISSUE TITLE
process_map() issue

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/processmapR#37]
Hi Gert,

Thank you for all these fundamental improvements of the bupaR package.

I have a problem with the process_map () function: when I try to produce a process map, RStudio's Viewer reports this error "Error: syntax in row 37 near" ("." I found that this occurs when the size of my data increases (for example, by moving filter_activity_frequency from 0.1 to 0.2).

Do you have some advice?

Thank you

**Comment by Nipi** [comment]
Probably it is related with the length of the name of the activity

**Comment by gertjanssenswillen** [comment]
Could you check whether there are some weird characters in the activity labels in question?
