### ISSUE TITLE
precedence_matrix

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/processmapR#4]
Hi, Gert. I'm using your useful package and I have an isseu on processmapR.

The precedence_matrix function return the following error:
Error in mutate_impl(.data, dots) : 
  Not compatible with requested type: [type=character; target=integer]

Thanks.

**Comment by gertjanssenswillen** [comment]
I cannot immediately replicate that error. Can you give me some more information:
- which arguments you used, if any?
- what is the result of calling traceback() after the error?

**Comment by Nipi** [comment]
Here a copy of the command and a copy of the traceback (evl in an eventlog object).

> evl %>% precedence_matrix("absolute")
Error in mutate_impl(.data, dots) : 
  Not compatible with requested type: [type=character; target=integer].


> traceback()
22: stop(list(message = "Not compatible with requested type: [type=character; target=integer].", 
        call = mutate_impl(.data, dots), cppstack = NULL))
21: .Call(`_dplyr_mutate_impl`, df, dots)
20: mutate_impl(.data, dots)
19: mutate.tbl_df(., antecedent = event_classifier, consequent = lead(event_classifier, 
        default = "End"))
18: mutate(., antecedent = event_classifier, consequent = lead(event_classifier, 
        default = "End"))
17: function_list[[k]](value)
16: withVisible(function_list[[k]](value))
15: freduce(value, `_function_list`)
14: `_fseq`(`_lhs`)
13: eval(quote(`_fseq`(`_lhs`)), env, env)
12: eval(quote(`_fseq`(`_lhs`)), env, env)
11: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
10: log %>% group_by(case_classifier, event_classifier, aid) %>% 
        summarize(ts = min(timestamp_classifier)) %>% group_by(case_classifier) %>% 
        arrange(ts) %>% mutate(antecedent = event_classifier, consequent = lead(event_classifier, 
        default = "End"))
9: precedence_matrix(., "absolute")
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: evl %>% precedence_matrix("absolute")

**Comment by gertjanssenswillen** [comment]
Issue should be solved now.

**Comment by Nipi** [comment]
Thanks a lot!
