### ISSUE TITLE
Secondary metric for the process_map

### ISSUE THREAD

**Issue by frkbr** [gertjanssenswillen/processmapR#40]
It would be nice to have a secondary metric in the `process_map` function to show both frequencies and waiting times on the edges. The secondary metric could have a slightly smaller font size (see Disco).

`process_map(performance(sum, "days"))` is an alternative to show the severity of waiting times, but a secondary metric would provide even more context.

**Comment by gertjanssenswillen** [comment]
This is a functionality that has been on the wish list for quite some time. I'm now refactoring the process map functions (separating the different types from the map itself, so that types can be changed or added more easily). Once that's done, the secondary metric will be easier to add. Hope to finish it during the next days.

**Comment by frkbr** [comment]
👍

**Comment by gertjanssenswillen** [comment]
Secondary functionality is added. 

![image](https://user-images.githubusercontent.com/8807203/49950649-80243080-fef8-11e8-8824-97fb8ac10b9d.png)

The arguments are currently `sec `and `sec_nodes `and `sec_edges`. They work the same as for the primary metric: you can use separate views for nodes and edges if you like. But if `sec` is provided, both nodes and edges will inherit this. 

These arguments use the same functions, i.e. `frequency`, `performance` and `custom`. Some of the arguments will be ignored if used for secondary, e.g. color info won't be used, only the values will be used.  (as in Disco). 

Currently, the primary values are shown first, and secondary values are shown second and between brackets. It's not possible (or at least not easy) to differentiate the format (e.g. shown secondary smaller or in grey); the whole node and edge labels use the same format.

If you have any suggestions about appearance or about the used terminology (argument names for instance), please share them!

**Comment by gertjanssenswillen** [comment]
Correct, brackets are added to edges now also.
