### ISSUE TITLE
process_map

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/processmapR#5]
Hi, Gert. I found that process_map function doesn't work well when type = perfomance().

Nodes are numbers instead of "actions" and the starting node seems to be a final node.

![cattura](https://user-images.githubusercontent.com/18727013/33877677-6a9e242c-df29-11e7-9252-e23e35e15612.PNG)

**Comment by gertjanssenswillen** [comment]
Strange. Is it possible to share (a subset of) the data you have, so I can see what's wrong? If so, send them to gert.janssenswillen@uhasselt.be. If not, I'll think of some tests you can do to find the problem.

In any case, thanks for highlighting these issues!

**Comment by Nipi** [comment]
Hello Gert, I am sorry, but it is not possible to share a subset of data at the moment.

But I used this function with default type and it works well.... it seems to be a problem with type = performance ().

In addition, in the portion of graph that I removed from screenshot is possible to read the "actions". The rappresentation I obtained from processmapR is mixed: some nodes are actions and others are numbers...but I don't have numbers as activity_id in my data.

Thanks a lot!

**Comment by gertjanssenswillen** [comment]
Ok, thanks anyhow. I hope to find the problem very soon.

**Comment by gertjanssenswillen** [comment]
I made a separate branch to test some things. Can you install this version of processmapR (in a clean R session):

devtools::install_github("gertjanssenswillen/processmapR", ref = "process_map_dev")

and show me the results of the process_map function? It will be a list with 3 data.frames (without confidential information).

**Comment by Nipi** [comment]
here you are, thanks 4 the support
[gert.zip](https://github.com/gertjanssenswillen/processmapR/files/1551645/gert.zip)

**Comment by gertjanssenswillen** [comment]
In your data, are there any missing values for the timestamp column?

**Comment by gertjanssenswillen** [comment]
Good, so I assume that's the problem. I will fix the code such that it can handle these missing values.

**Comment by gertjanssenswillen** [comment]
I pushed some fixes to the separate branch. Could you try if the result is improved now? (sorry I don't have an appropriate event log right now to test it myself)

**Comment by gertjanssenswillen** [comment]
I have pushed another fix which I think will solve the issues with the arcs.

**Comment by Nipi** [comment]
The problem is solved! Thanks a lot!

**Comment by gertjanssenswillen** [comment]
Issue solved by pull request #6
