### ISSUE TITLE
process_map()

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/processmapR#7]
Hi Gert,

I'm using the process_map() function. I'm not able to understand why the activity is sometimes printed white and sometimes printed black when the node in process map is colored white/pink.

The problem is that it is impossible to read activity in some cases .

Thanks.

**Comment by gertjanssenswillen** [comment]
Hi, this is a known problem which I hope to solve very soon. Sorry for the inconvience.

**Comment by Nipi** [comment]
Thanks

**Comment by gertjanssenswillen** [comment]
I have pushed a small fix to the process map function. Not sure if it will solve the problem, so please let me know.
