### ISSUE TITLE
pass render=TRUE 

### ISSUE THREAD

**Issue by spedygiorgio** [gertjanssenswillen/processmapR#9]
I am using the process_map within an R MARKDOWN... When there are too many cases the code wait untill user confirms he wants to plot regardless possible ununderstandable graph. Is it possible to pass programmatically the confirmation, e.g., using a parameter lot_of_traces_behavious = c("ask", "N", Y")

Thanks in advance for the attention
```
myevnlog %>% process_map()
You are about to draw a process map with a lot of traces.
        This might take a long time. Try to filter your event log. Are you sure you want to proceed?
Y/N: Y
Warning messages:
1: In bind_rows_(x, .id) :
  binding factor and character vector, coercing into character vector
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
```

**Comment by gertjanssenswillen** [comment]
I have added an argument force = T (default is F) to surpass the check

**Comment by spedygiorgio** [comment]
Great, Thanks for the update

Il gio 21 dic 2017, 13:16 Gert Janssenswillen <notifications@github.com> ha
scritto:
